FROM python:3.6.10

# Установка зависимостей
RUN pip install torch torchvision librosa numpy

# Добавление кода модели в контейнер
COPY model.py /app/
WORKDIR /app

# Команда для запуска модели
CMD ["python", "model.py"]
